export const actionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    DELETEPRODUCT : 'DELETEPRODUCT',
    SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',
    LOGIN: 'LOGIN',
    SIGNIN : 'SIGNIN',
    LOGOUT: 'LOGOUT',
    ADDTOCART: 'ADDTOCART',
    REMOVEFROMCART: 'REMOVEFROMCART',
    CLEARCART: 'CLEARCART'
    
}